image: node:12.10.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test_async:
  script:
    - npm run test:cover
  artifacts:
    paths:
      - coverage

pages:
  stage: deploy
  dependencies:
    - test_async
  script:
    - npm run docs:build
    - cp -r coverage/* public/
  artifacts:
    paths:
      - public
  only:
    - master
