image: node:latest

cache:
  paths:
  - node_modules/

test_async:
  script:
   - npm install
   - npm run test

pages:
  stage: deploy
  script:
   - npm install
   - npm run build-doc
  artifacts:
    paths:
    - jsdoc
  only:
  - master