image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
   - npm run build-doc
  artifacts:
    paths:
    - jsdoc
  only:
  - master
  
 test:
  stage: test
  script:
  - npm run test
