image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

test_async:
  script:
   - npm run test

pages:
  stage: deploy
  script:
   - npm run build-doc
  artifacts:
    paths:
    - jsdoc
  only:
  - master
  
